name: Build Distribution Zip

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create distribution zip
      run: |
        zip -r ai-development-business-case.zip . -x '*.git*' '*.github*'

    - name: Upload zip artifact
      uses: actions/upload-artifact@v3
      with:
        name: ai-development-business-case
        path: ai-development-business-case.zip

